### ISSUE TITLE
Average command failed with stack trace

### ISSUE THREAD

**Issue by stepanov-standy** [AsolyticsOpenSource/asolytics#2]
Hi Team,

First of all let me say thank you for the great project!

I was able to successfully install and use it, but looks like I have found one issue with "average" command when I try to use it with any app from Google Play Store:

```
Загальна кількість відгуків: 1720.00
Загальна кількість завантажень: від 1000001 до 5000000
Traceback (most recent call last):
  File "/Users/standy/miniconda3/bin/asolytics", line 8, in <module>
    sys.exit(main())
  File "/Users/standy/miniconda3/lib/python3.10/site-packages/asolytics/asolytics.py", line 689, in main
    average_install_in_Google_Play(args.average, gl)
  File "/Users/standy/miniconda3/lib/python3.10/site-packages/asolytics/asolytics.py", line 455, in average_install_in_Google_Play
    button_deteils.pop(4).click()
  File "/Users/standy/miniconda3/lib/python3.10/site-packages/selenium/webdriver/remote/webelement.py", line 93, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/Users/standy/miniconda3/lib/python3.10/site-packages/selenium/webdriver/remote/webelement.py", line 410, in _execute
    return self._parent.execute(command, params)
  File "/Users/standy/miniconda3/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 444, in execute
    self.error_handler.check_response(response)
  File "/Users/standy/miniconda3/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 249, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: Element <button class="VfPpkd-Bz112c-LgbsSe yHy1rc eT1oJ mN1ivc LS2TS"> could not be scrolled into view
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:188:5
ElementNotInteractableError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:348:5
webdriverClickElement@chrome://remote/content/marionette/interaction.sys.mjs:150:11
interaction.clickElement@chrome://remote/content/marionette/interaction.sys.mjs:119:11
clickElement@chrome://remote/content/marionette/actors/MarionetteCommandsChild.sys.mjs:202:29
receiveMessage@chrome://remote/content/marionette/actors/MarionetteCommandsChild.sys.mjs:84:31
```

Is it due to some layout changes on the page?

**Comment by AsolyticsOpenSource** [comment]
Thank you for writing about this. I fixed this issue today.
Update with the command: pip install asolytics --upgrade
